import type { NextPage } from "next";
import Head from "next/head";
import Welcome from "@components/Welcome";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="h-screen flex flex-col justify-center align-middle text-center">
          <Welcome />
          <h2 className="mx-auto text-lg md:text-3xl">
            Next.js with TypeScript, Tailwind CSS, and tests!
          </h2>
        </div>
      </main>
    </div>
  );
};

export default Home;
